spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: false
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create-drop
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/book_manager?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
#    username: root
#    password: Rlatjrwls0!
#    initialization-mode: always
server:
  port: 8070
